// Calculator UI labels for all supported locales
// These are the ~25 hardcoded strings in the calculator component

export const CALCULATOR_LABELS = {
  en: {
    selectModel: "Select model...",
    placeholder: "Start typing or paste your text here...",
    clear: "Clear",
    paste: "Paste",
    example: "Example",
    exampleText: "Explain quantum computing in simple terms.",
    tokens: "Tokens",
    words: "Words",
    chars: "Chars",
    charsLabel: "chars",
    inputCost: "Input Cost",
    context: "Context",
    input: "INPUT",
    output: "OUTPUT",
    outputEst: "(EST)",
    total: "TOTAL",
    copyStats: "Copy Stats",
    shareLink: "Share Link",
    tokenVisualizer: "Token Visualizer",
    colored: "Colored",
    tokenIds: "Token IDs",
    typeToSeeTokens: "Type text above to see tokenization…",
    legend: "Legend:",
    word: "Word",
    punctuation: "Punct",
    subword: "Subword",
    space: "Space",
    upload: "Upload",
  },
  de: {
    selectModel: "Modell auswählen...",
    placeholder: "Text eingeben oder hier einfügen...",
    clear: "Löschen",
    paste: "Einfügen",
    example: "Beispiel",
    exampleText: "Erkläre Quantencomputing in einfachen Worten.",
    tokens: "Tokens",
    words: "Wörter",
    chars: "Zeichen",
    charsLabel: "Zeichen",
    inputCost: "Eingabekosten",
    context: "Kontext",
    input: "INPUT",
    output: "OUTPUT",
    outputEst: "(EST)",
    total: "GESAMT",
    copyStats: "Stats kopieren",
    shareLink: "Link teilen",
    tokenVisualizer: "Token Visualizer",
    colored: "Farbig",
    tokenIds: "Token-IDs",
    typeToSeeTokens: "Text eingeben, um Tokenisierung zu sehen…",
    legend: "Legende:",
    word: "Wort",
    punctuation: "Satzzeichen",
    subword: "Subwort",
    space: "Leerzeichen",
    upload: "Hochladen",
  },
  fr: {
    selectModel: "Sélectionner le modèle...",
    placeholder: "Commencez à taper ou collez votre texte ici...",
    clear: "Effacer",
    paste: "Coller",
    example: "Exemple",
    exampleText: "Expliquez l informatique quantique en termes simples.",
    tokens: "Jetons",
    words: "Mots",
    chars: "Carac.",
    charsLabel: "carac.",
    inputCost: "Dépense",
    context: "Contexte",
    input: "ENTRÉE",
    output: "SORTIE",
    outputEst: "(EST)",
    total: "TOTAL",
    copyStats: "Copier stats",
    shareLink: "Partager",
    tokenVisualizer: "Visualiseur de Jetons",
    colored: "Coloré",
    tokenIds: "IDs de Jetons",
    typeToSeeTokens: "Tapez du texte pour voir la tokenisation…",
    legend: "Légende :",
    word: "Mot",
    punctuation: "Ponctuation",
    subword: "Sous-mot",
    space: "Espace",
    upload: "Téléverser",
  },
  es: {
    selectModel: "Seleccionar modelo...",
    placeholder: "Escribe o pega texto para contar tokens en tiempo real...",
    clear: "Limpiar",
    paste: "Pegar",
    example: "Ejemplo",
    exampleText: "Explica la computación cuántica en términos simples.",
    tokens: "Tokens",
    words: "Palabras",
    chars: "Caracteres",
    charsLabel: "caracteres",
    inputCost: "Costo entrada",
    context: "Contexto",
    input: "ENTRADA",
    output: "SALIDA",
    outputEst: "(EST)",
    total: "TOTAL",
    copyStats: "Copiar stats",
    shareLink: "Compartir",
    tokenVisualizer: "Visualizador de Tokens",
    colored: "Coloreado",
    tokenIds: "IDs de Token",
    typeToSeeTokens: "Escribe texto para ver la tokenización…",
    legend: "Leyenda:",
    word: "Palabra",
    punctuation: "Puntuación",
    subword: "Subpalabra",
    space: "Espacio",
    upload: "Subir",
  },
  ja: {
    selectModel: "モデルを選択...",
    placeholder: "テキストを入力または貼り付けてください...",
    clear: "クリア",
    paste: "貼り付け",
    example: "例を見る",
    exampleText: "量子コンピューティングを簡単な言葉で説明してください。",
    tokens: "トークン",
    words: "単語",
    chars: "文字",
    charsLabel: "文字",
    inputCost: "入力コスト",
    context: "コンテキスト",
    input: "入力",
    output: "出力",
    outputEst: "（推定）",
    total: "合計",
    copyStats: "統計をコピー",
    shareLink: "リンクを共有",
    tokenVisualizer: "トークンビジュアライザー",
    colored: "カラー",
    tokenIds: "トークンID",
    typeToSeeTokens: "テキストを入力してトークン化を表示…",
    legend: "凡例:",
    word: "単語",
    punctuation: "句読点",
    subword: "サブワード",
    space: "スペース",
    upload: "アップロード",
  },
  "pt-BR": {
    selectModel: "Selecionar modelo...",
    placeholder: "Digite ou cole texto para contar tokens em tempo real...",
    clear: "Limpar",
    paste: "Colar",
    example: "Exemplo",
    exampleText: "Explique a computação quântica em termos simples.",
    tokens: "Tokens",
    words: "Palavras",
    chars: "Caracteres",
    charsLabel: "caracteres",
    inputCost: "Custo entrada",
    context: "Contexto",
    input: "ENTRADA",
    output: "SAÍDA",
    outputEst: "(EST)",
    total: "TOTAL",
    copyStats: "Copiar stats",
    shareLink: "Compartilhar",
    tokenVisualizer: "Visualizador de Tokens",
    colored: "Colorido",
    tokenIds: "IDs de Token",
    typeToSeeTokens: "Digite texto para ver a tokenização…",
    legend: "Legenda:",
    word: "Palavra",
    punctuation: "Pontuação",
    subword: "Subpalavra",
    space: "Espaço",
    upload: "Enviar",
  },
  ko: {
    selectModel: "모델 선택...",
    placeholder: "텍스트를 입력하거나 붙여넣으세요...",
    clear: "지우기",
    paste: "붙여넣기",
    example: "예제",
    exampleText: "양자 컴퓨팅을 쉬운 말로 설명해주세요.",
    tokens: "토큰",
    words: "단어",
    chars: "문자",
    charsLabel: "문자",
    inputCost: "입력 비용",
    context: "컨텍스트",
    input: "입력",
    output: "출력",
    outputEst: "(추정)",
    total: "합계",
    copyStats: "통계 복사",
    shareLink: "링크 공유",
    tokenVisualizer: "토큰 시각화 도구",
    colored: "컬러",
    tokenIds: "토큰 ID",
    typeToSeeTokens: "텍스트를 입력하여 토큰화 확인…",
    legend: "범례:",
    word: "단어",
    punctuation: "구두점",
    subword: "서브워드",
    space: "공백",
    upload: "업로드",
  },
  zh: {
    selectModel: "选择模型...",
    placeholder: "输入或粘贴文本以实时统计token...",
    clear: "清除",
    paste: "粘贴",
    example: "示例",
    exampleText: "用简单的语言解释量子计算。",
    tokens: "Token",
    words: "词数",
    chars: "字符",
    charsLabel: "字符",
    inputCost: "输入成本",
    context: "上下文",
    input: "输入",
    output: "输出",
    outputEst: "（估计）",
    total: "合计",
    copyStats: "复制统计",
    shareLink: "分享链接",
    tokenVisualizer: "Token可视化器",
    colored: "彩色",
    tokenIds: "Token ID",
    typeToSeeTokens: "输入文本查看Token化…",
    legend: "图例：",
    word: "单词",
    punctuation: "标点",
    subword: "子词",
    space: "空格",
    upload: "上传",
  },
};
